# Discord
DISCORD_TOKEN: hogehoge
GUILD_ID: 1234567890

# BOT
globalCommands: false
allows:
  - switch
  - refresh
  - imagine

defaultStyle: Low Quality + Bad Anatomy
defaultAspect: "2:3"
defaultSampler: DPM++ 2M Karras

# AUTOMATIC1111's Web UI
host: http://localhost:7860
