# Discord
DISCORD_TOKEN: hogehoge
GUILD_ID: "1234567890"

# BOT
globalCommands: false
allows:
  - switch
  - refresh
  - imagine
  - info
  - status
  # - neko

defaultParameters:
  style: ""
  sampler: "DPM++ 2M Karras"
  width: 512
  height: 768
  highresFix: false
  clipSkip: 2

additionalParameters:
  promptPrefix: "masterpiece, exceptional"
  promptSuffix: "ultra detailed"
  negativePromptPrefix: "badquality, bad anatomy"
  negativePromptSuffix: ""

serverType: "AUTOMATIC1111"

# AUTOMATIC1111's Web UI
host: http://localhost:7860
